<?php

declare(strict_types=1);

namespace SlFomin\PwaLaravel\Console;

use Illuminate\Console\Command;
use Illuminate\Contracts\Events\Dispatcher;
use SlFomin\PwaLaravel\Events\ManifestPublished;
use SlFomin\PwaLaravel\Manifest\ManifestBuilder;
use Throwable;

final class PublishManifestCommand extends Command
{
    protected $signature = 'pwa:publish-manifest
        {--path= : Custom output path (default: from config pwa.manifest.static_path)}
        {--pretty : Pretty-print the JSON output}';

    protected $description = 'Generate static manifest.webmanifest from config (useful without a Vite build step)';

    public function handle(Dispatcher $events): int
    {
        $data = config('pwa.manifest.data', []);

        if (! is_array($data)) {
            $this->error('pwa.manifest.data is not an array. Check your config/pwa.php.');

            return self::FAILURE;
        }

        $manifest = ManifestBuilder::make($data);

        try {
            $manifest->validate();
        } catch (Throwable $e) {
            $this->error('Invalid manifest config: '.$e->getMessage());
            $this->line('  Fix the values in <info>config/pwa.php</info> under <info>manifest.data</info>.');

            return self::FAILURE;
        }

        $path = $this->option('path') ?? config('pwa.manifest.static_path');

        if (! is_string($path)) {
            $this->error('Output path is not configured. Use --path or set pwa.manifest.static_path.');

            return self::FAILURE;
        }

        $dir = dirname($path);

        if (! is_dir($dir) && ! mkdir($dir, 0755, true) && ! is_dir($dir)) {
            $this->error("Failed to create directory: {$dir}");

            return self::FAILURE;
        }

        $flags = JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE;

        if ($this->option('pretty')) {
            $flags |= JSON_PRETTY_PRINT;
        }

        $json = $manifest->toJson($flags);

        $bytes = file_put_contents($path, $json);

        if ($bytes === false) {
            $this->error("Failed to write manifest to: {$path}");

            return self::FAILURE;
        }

        $events->dispatch(new ManifestPublished($path, $manifest, $bytes));

        $this->info("Manifest published: {$path}");
        $this->line('  Size: '.number_format(strlen($json) / 1024, 2).' KB');
        $this->line('  Icons: '.count($manifest->get('icons', [])));

        $this->newLine();
        $this->line('<fg=yellow>Note:</> This file is normally generated by Vite/vite-plugin-pwa during build.');
        $this->line('  Use this command only if you are not using a Vite build step.');

        return self::SUCCESS;
    }
}
